from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Enum as SQLAlchemyEnum, JSON
from sqlalchemy.orm import relationship
from .database import Base
import datetime
import enum

# Define an Enum for user roles to ensure data consistency
class UserRole(str, enum.Enum):
    USER = "user"
    ADMIN = "admin"

class User(Base):
    """
    SQLAlchemy model for the 'users' table.
    Now includes a 'role' to distinguish between regular users and admins.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
    # Add the role column, with a default value of 'user'
    role = Column(SQLAlchemyEnum(UserRole), nullable=False, default=UserRole.USER)

    # This creates a one-to-one relationship with the Subscription model.
    subscription = relationship("Subscription", back_populates="user", uselist=False, cascade="all, delete-orphan")
    generated_exams = relationship("GeneratedExam", back_populates="user", cascade="all, delete-orphan")
    exam_attempts = relationship("ExamAttempt", back_populates="user", cascade="all, delete-orphan")

class Subscription(Base):
    """
    SQLAlchemy model for the 'subscriptions' table.
    This table will track the subscription status for each user.
    """
    __tablename__ = "subscriptions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    payment_customer_id = Column(String, unique=True, index=True, nullable=True)
    is_active = Column(Boolean, default=False)
    expires_at = Column(DateTime, nullable=True)
    
    user = relationship("User", back_populates="subscription")

class GeneratedExam(Base):
    """
    Stores exams generated by users that haven't been attempted yet.
    Once attempted, the exam moves to ExamAttempt table.
    """
    __tablename__ = "generated_exams"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    exam_type = Column(String, nullable=False)  # CAT or GATE
    exam_name = Column(String, nullable=False)
    stream = Column(String, nullable=True)
    year = Column(Integer, nullable=True)
    generated_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    exam_data = Column(JSON, nullable=False)  # Full exam structure
    is_attempted = Column(Boolean, default=False)

    user = relationship("User", back_populates="generated_exams")

class ExamAttempt(Base):
    """
    Stores historical exam submissions for users with detailed statistics.
    """
    __tablename__ = "exam_attempts"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    generated_exam_id = Column(Integer, ForeignKey("generated_exams.id"), nullable=True)
    exam_type = Column(String, nullable=False)  # CAT or GATE
    exam_name = Column(String, nullable=False)
    stream = Column(String, nullable=True)
    year = Column(Integer, nullable=True)
    score = Column(Integer, nullable=True)
    total_questions = Column(Integer, nullable=False)
    correct_answers = Column(Integer, nullable=False)
    wrong_answers = Column(Integer, nullable=False)
    unanswered = Column(Integer, nullable=False)
    percentage = Column(Integer, nullable=True)
    time_taken = Column(Integer, nullable=True)  # in seconds
    submitted_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    exam_data = Column(JSON, nullable=False)

    user = relationship("User", back_populates="exam_attempts")
    generated_exam = relationship("GeneratedExam")

